# Broadcast Messages                                                                         

broadcasts:
  - "Check out my website! google.com"
  - "Be sure to follow my twitter! twitter.com"
  - "Don't forget to wash your hands!"
  - "Be sure to leave a follow if you're enjoying the stream!"
